namespace SpecDocGenerator.Core.Models;

/// <summary>
/// Summary level for hierarchical summarization
/// </summary>
public enum SummaryLevel
{
    Function,    // Individual function/method
    File,        // File level
    Module,      // Module/directory level
    System       // System/project level
}

/// <summary>
/// Represents a summary generated by LLM
/// </summary>
public class Summary
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public SummaryLevel Level { get; set; }
    public string Content { get; set; } = string.Empty;
    public string SourceId { get; set; } = string.Empty;
    public List<string> ChildSummaryIds { get; set; } = new();
    public Dictionary<string, string> Metadata { get; set; } = new();
}
